export const productsExample = [
    {
        id: 1,
        nombre: 'Pantalon1',
        precio: 30000,
        imagen: 'src/assets/images/pantalon.jpg',
        descripcion: 'Pantalon de vestir para hombre',
        cantidad: {
            Pantalon: 1,
            Saco: 2,
            Chaleco: 3,
            Corbata: 4,
            camisa: 5,
        },
        color: 'verde',
    },
    {
        id: 2,
        nombre: 'Pantalon2',
        precio: 20000,
        imagen: 'src/assets/images/pantalon.jpg',
        descripcion: 'Pantalon de vestir para hombre',
        cantidad: {
            Pantalon: 1,
            Saco: 2,
            Chaleco: 3,
            Corbata: 4,
            camisa: 5,
        },
        color: 'verde',
    },
    {
        id: 3,
        nombre: 'Pantalon3',
        precio: 40000,
        imagen: 'src/assets/images/pantalon.jpg',
        descripcion: 'Pantalon de vestir para hombre',
        cantidad: {
            Pantalon: 1,
            Saco: 2,
            Chaleco: 3,
            Corbata: 4,
            camisa: 5,
        },
        color: 'verde',
    },
    {
        id: 4,
        nombre: 'Pantalon4',
        precio: 50000,
        imagen: 'src/assets/images/pantalon.jpg',
        descripcion: 'Pantalon de vestir para hombre',
        cantidad: {
            Pantalon: 1,
            Saco: 2,
            Chaleco: 3,
            Corbata: 4,
            camisa: 5,
        },
        color: 'verde',
    },
    {
        id: 5,
        nombre: 'Pantalon5',
        precio: 60000,
        imagen: 'src/assets/images/pantalon.jpg',
        descripcion: 'Pantalon de vestir para hombre',
        cantidad: {
            Pantalon: 1,
            Saco: 2,
            Chaleco: 3,
            Corbata: 4,
            camisa: 5,
        },
        color: 'verde',
    },
];
